//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/TouchActionAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchActionAsset: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchActionAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchActionAsset"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""41fbde1d-5677-4785-a392-5211df566d7d"",
            ""actions"": [
                {
                    ""name"": ""SingleTapPosition"",
                    ""type"": ""Value"",
                    ""id"": ""fc197124-b78c-4fd0-8d24-9f76823050d8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SingleTapPressed"",
                    ""type"": ""Button"",
                    ""id"": ""31d32a8e-ba47-4634-86fa-f4e5abf1e589"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3cf5642e-bcdc-4383-b658-959125a369a2"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SingleTapPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31b619a6-f50d-408a-ac31-0aa0dcc5d6a4"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SingleTapPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_SingleTapPosition = m_Touch.FindAction("SingleTapPosition", throwIfNotFound: true);
        m_Touch_SingleTapPressed = m_Touch.FindAction("SingleTapPressed", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
    private readonly InputAction m_Touch_SingleTapPosition;
    private readonly InputAction m_Touch_SingleTapPressed;
    public struct TouchActions
    {
        private @TouchActionAsset m_Wrapper;
        public TouchActions(@TouchActionAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @SingleTapPosition => m_Wrapper.m_Touch_SingleTapPosition;
        public InputAction @SingleTapPressed => m_Wrapper.m_Touch_SingleTapPressed;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void AddCallbacks(ITouchActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
            @SingleTapPosition.started += instance.OnSingleTapPosition;
            @SingleTapPosition.performed += instance.OnSingleTapPosition;
            @SingleTapPosition.canceled += instance.OnSingleTapPosition;
            @SingleTapPressed.started += instance.OnSingleTapPressed;
            @SingleTapPressed.performed += instance.OnSingleTapPressed;
            @SingleTapPressed.canceled += instance.OnSingleTapPressed;
        }

        private void UnregisterCallbacks(ITouchActions instance)
        {
            @SingleTapPosition.started -= instance.OnSingleTapPosition;
            @SingleTapPosition.performed -= instance.OnSingleTapPosition;
            @SingleTapPosition.canceled -= instance.OnSingleTapPosition;
            @SingleTapPressed.started -= instance.OnSingleTapPressed;
            @SingleTapPressed.performed -= instance.OnSingleTapPressed;
            @SingleTapPressed.canceled -= instance.OnSingleTapPressed;
        }

        public void RemoveCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnSingleTapPosition(InputAction.CallbackContext context);
        void OnSingleTapPressed(InputAction.CallbackContext context);
    }
}
